### ISSUE TITLE
Typos in documentation page lovelace_config.yaml examples

### ISSUE THREAD

**Issue by jayscovill** [Anwen747/weatherbit-weather-card#2]
Got this all up and running! Awesome work porting this over from the Dark Sky card!

I noticed a couple of typos that I had to fix to make the card work.

On the main documentation page in the template sensor wbit_alt_wind it still references "dark_sky":

`wbit_alt_wind:
  value_template: >-
                  {% set winddir = ['North','North-Northeast','Northeast','East-Northeast','East','East-Southeast','Southeast','South-Southeast','South','South-Southwest','Southwest','West-Southwest','West','West-Northwest','Northwest','North-Northwest','North'] %}
                  {{ states('sensor.dark_sky_wind_speed') | round }} mi/h from the {{ winddir[((states('sensor.dark_sky_wind_bearing') | float / 360)*16) | round]}}`

And in your lovelace_config.yaml example the sun entity is referenced as "entity_sun: sun.sun" instead of just "entity: sun.sun"

`
entity_summary_5: sensor.wbit_day6_text
entity_sun: sun.sun
entity_daytime_high: sensor.wbit_day1_high
`

Just to save any copy/pasters out there like me some hunting in the future!

**Comment by Anwen747** [comment]
Really glad you were able to get it working.  Thanks for pointing out the Dark Sky typo - missed that when I was editing the documentation.  I've updated the documentation, including the card picture and the config.

It is ```entity_sun: sun.sun```, that is not a typo.  The Lovelace config shown is taken directly from my working instance.

**Comment by jayscovill** [comment]
Oh, interesting. I had to change it to entity: sun.sun to display the card.  Wonder why there's a difference there?

**Comment by Anwen747** [comment]
I have no idea why that is working for you. If I change my card config to ```entity: sun.sun```, I see the card but there the sunrise and sunset entries disappear.
